### ISSUE TITLE
Spring cloud Dalston.SR1版本使用Feign和Eureka的ContextClosedEvent事件处理问题

### ISSUE THREAD

**Issue by dengly** [dengly/spring-cloud-study#4]
我们公司使用Spring cloud Dalston.SR1版本，且使用了Feign和Eureka。

由于考虑到性能问题，有一些日志是定时批量写库，但这样的话就需要在程序退出前，将没有写库的日志也要写进去，而且需要依赖到Spring的bean注入，所以没有使用虚拟机的关闭钩子。而Spring本身提供了事件监听器，所以就通过监听```ContextClosedEvent```事件。

在程序退出时会报以下错误，(这可能是Spring cloud Dalston.SR1版本的bug，听说在新版解决了这个问题)
```
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaAutoServiceRegistration': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:216)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:280)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:250)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:389)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:994)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:76)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:272)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
	at org.springframework.boot.SpringApplication.close(SpringApplication.java:1222)
	at org.springframework.boot.SpringApplication.exit(SpringApplication.java:1209)
	at com.zzwtec.device.DeviceApplication.main(DeviceApplication.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```
在[spring-cloud的#2099](https://github.com/spring-cloud/spring-cloud-netflix/issues/2099) 和[spring-cloud的#1952](https://github.com/spring-cloud/spring-cloud-netflix/issues/1952)也有提及这个错误，但是网友提供的方法也没能解决问题，也没达到想要的效果。

在调试中发现，Spring 在回调监听器时，是通过调用 ```org.springframework.context.event.SimpleApplicationEventMulticaster```的```multicastEvent(final ApplicationEvent event, ResolvableType eventType)``方法来回调监听器的。而在这里面有个执行器，先判断执行器是否为null，如果为null，则单线程执行；不为null，则启用多线程执行。

在 Spring cloud Dalston.SR1 这个版本里，使用 Feign 和 Eureka ，在关闭时会报 ```org.springframework.beans.factory.BeanCreationNotAllowedException```异常，且自己添加的```ContextClosedEvent```事件监听器调用顺序比框架的要慢，如果没有设置 ```org.springframework.context.event.SimpleApplicationEventMulticaster```的执行器，则由于异常而导致我们的事件监听器没有被调用。为了能实现在程序关闭前处理业务，则需要给```org.springframework.beans.factory.BeanCreationNotAllowedException```设置执行器，同时采用 ```ContextClosedEvent```事件监听器处理。

**Comment by dengly** [comment]
参考例子
```
public static void main(String[] args) {
    ConfigurableApplicationContext context = SpringApplication.run(Application.class, args);
    SimpleApplicationEventMulticaster simpleApplicationEventMulticaster = context.getBean(SimpleApplicationEventMulticaster.class);
    simpleApplicationEventMulticaster.setTaskExecutor(Executors.newSingleThreadExecutor());
}

@EventListener
public void close(ApplicationEvent event){
    if(event instanceof ContextClosedEvent){ // 应用关闭事件
        System.out.println("程序退出前操作");
    }
}
```
